//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NurseRequest
    {
        public int RequestId { get; set; }
        public int TrainerId { get; set; }
        public int PokemonId { get; set; }
        public string Status { get; set; }
        public System.DateTime RequestDate { get; set; }
    
        public virtual Pokemon Pokemon { get; set; }
        public virtual User User { get; set; }
    }
}
