//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokedex
    {
        public int PokemonId { get; set; }
        public int EvolutionId { get; set; }
        public decimal Weight { get; set; }
        public int MaxLifePoints { get; set; }
        public string Description { get; set; }
    
        public virtual Pokemon Pokemon { get; set; }
    }
}
