//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int TeamID { get; set; }
        public int UserId { get; set; }
        public int PokemonId1 { get; set; }
        public int PokemonId2 { get; set; }
        public int PokemonId3 { get; set; }
        public int PokemonId4 { get; set; }
        public string Description { get; set; }
    
        public virtual Pokemon Pokemon { get; set; }
        public virtual Pokemon Pokemon1 { get; set; }
        public virtual Pokemon Pokemon2 { get; set; }
        public virtual Pokemon Pokemon3 { get; set; }
        public virtual User User { get; set; }
    }
}
